"""YAML configuration schema and loading utilities."""

from atha.config.loader import LoadedAnalysisConfig, load_analysis_config, load_config_folder
from atha.config.balances import BalanceConfig, BalanceResidual, balance_configs, wrap_problem_with_balances
from atha.config.controllers import (
    ControllerStateInfo,
    controller_execution_order,
    controller_evaluation_period,
    controller_input_paths,
    controller_output_paths,
    controller_reset_state_values,
    controller_state_infos,
    evaluate_controllers,
    evaluate_dynamic_controllers,
)
from atha.config.mission_phases import (
    PhaseTransition,
    controller_hold_when_inactive,
    controller_is_active,
    controller_should_reset_on_enter,
    detect_phase_transition,
    resolve_phase_name,
)
from atha.config.maps import build_performance_map, build_performance_maps
from atha.config.perturbations import apply_path_overrides, flatten_overrides
from atha.config.schedules import (
    evaluate_boundary_conditions,
    evaluate_operating_targets,
    evaluate_schedule,
    evaluate_timing_events,
)
from atha.config.transients import SUPPORTED_TRANSIENT_TYPES, TransientBlock, TransientSystem
from atha.config.schema import (
    AnalysisConfig,
    BoundaryConditionsConfig,
    ComponentConfig,
    ConfigError,
    ConnectionConfig,
    ControllerConfig,
    EngineConfig,
    MapBindingConfig,
    MapConfig,
    OperatingConditionsConfig,
    PhaseConfig,
    TelemetryConfig,
    TimingConfig,
    TransientConfig,
)

__all__ = [
    "AnalysisConfig",
    "BoundaryConditionsConfig",
    "ComponentConfig",
    "ConfigError",
    "ConnectionConfig",
    "ControllerConfig",
    "ControllerStateInfo",
    "EngineConfig",
    "LoadedAnalysisConfig",
    "MapBindingConfig",
    "MapConfig",
    "OperatingConditionsConfig",
    "PhaseConfig",
    "PhaseTransition",
    "TelemetryConfig",
    "TimingConfig",
    "TransientConfig",
    "TransientBlock",
    "TransientSystem",
    "SUPPORTED_TRANSIENT_TYPES",
    "load_analysis_config",
    "load_config_folder",
    "BalanceConfig",
    "BalanceResidual",
    "balance_configs",
    "wrap_problem_with_balances",
    "build_performance_map",
    "build_performance_maps",
    "apply_path_overrides",
    "controller_execution_order",
    "controller_evaluation_period",
    "controller_hold_when_inactive",
    "controller_input_paths",
    "controller_is_active",
    "controller_output_paths",
    "controller_reset_state_values",
    "controller_should_reset_on_enter",
    "controller_state_infos",
    "detect_phase_transition",
    "evaluate_boundary_conditions",
    "evaluate_controllers",
    "evaluate_dynamic_controllers",
    "evaluate_operating_targets",
    "evaluate_schedule",
    "evaluate_timing_events",
    "flatten_overrides",
    "resolve_phase_name",
]
