name: valve_volume_transient
engine: engine.yaml
boundary_conditions: boundaries.yaml
transients: transients.yaml
timings: timings.yaml
telemetry: telemetry.yaml
solver:
  transient:
    method: Radau
    rtol: 1.0e-7
    atol: 1.0e-2
    max_step: 0.01
analysis:
  type: valve_volume_transient
  time:
    start_s: -1.0
    end_s: 10.0
  model:
    initial_P: 101325.0
    initial_mdot_out: 0.0
  output:
    csv: valve_volume_transient.csv
    plot: valve_volume_transient.png
