name: valve_volume_transient
units: SI
components:
  valve:
    type: Valve
    transient: valve_actuator
    parameters:
      CdA: 2.2e-6
  downstream_volume:
    type: GasVolume
    parameters:
      volume: 0.08
      gas_R: 287.0
      gas_T: 300.0
      gamma: 1.4
  outlet:
    type: OutletInertia
    parameters:
      outlet_resistance: 1.0e7
      outlet_inertance: 9.0e6
connections: []
