name: ffsc_lox_methane_boundaries
time_unit: s
conditions:
  lox_tank.outlet.P: {value: 4.0e5, units: Pa}
  lox_tank.outlet.T: {value: 91.0, units: K}
  fuel_tank.outlet.P: {value: 4.0e5, units: Pa}
  fuel_tank.outlet.T: {value: 108.0, units: K}
  nozzle.ambient.P: {value: 0.0, units: Pa}
  lox_shaft.omega_override: {value: 3351.0321638291125, units: rad/s}
  fuel_shaft.omega_override: {value: 2827.4333882308138, units: rad/s}
