name: tca_propellant_valve_transient
engine: engine.yaml
boundary_conditions: boundaries.yaml
transients: transients.yaml
timings: timings.yaml
telemetry: telemetry.yaml
solver:
  transient:
    method: Radau
    rtol: 1.0e-7
    atol: 1.0e-6
    max_step: 0.005
analysis:
  type: tca_propellant_valve_transient
  time:
    start_s: 0.0
    end_s: 5.0
  model:
    initial_Pc: 101325.0
    initial_mdot_methane: 5
    initial_mdot_lox: 10
  output:
    csv: tca_propellant_valve_transient.csv
    plot: tca_propellant_valve_transient.png
