name: tca_propellant_valve_timings
events:
  - target: methane_valve.command
    schedule:
      type: step
      time: 0.0
      initial: 0.2
      final: 1.0
  - target: lox_valve.command
    schedule:
      type: step
      time: 1.0
      initial: 0.2
      final: 1.0
