name: tca_pms_null_controllers
controllers:
  mdot_total:
    type: null
    input: targets.pms.mdot_total
    output: commands.pms.mdot_total
  OF:
    type: null
    input: targets.pms.OF
    output: commands.pms.OF
  injector_mass_flow_split:
    type: of_mass_flow_split
    inputs:
      mdot_total: targets.pms.mdot_total
      OF: targets.pms.OF
    outputs:
      oxidizer: lox_inj.inlet.mdot
      fuel: fuel_inj.inlet.mdot
