name: ffsc_dae_acceptance_controller
controllers:
  methane_crossover_mdot_p:
    type: proportional
    inputs:
      target: targets.mdot_total
      measurement: measurements.mdot_total
    output: methane_crossover_valve.command
    parameters:
      bias: 0.25
      gain: 0.15
      lower_limit: 0.05
      upper_limit: 1.00
  lox_crossover_of_p:
    type: proportional
    inputs:
      target: targets.OF
      measurement: measurements.OF
    output: lox_crossover_valve.command
    parameters:
      bias: 0.50
      gain: -0.35
      lower_limit: 0.05
      upper_limit: 1.00
