name: ffsc_dae_acceptance_controller
evaluation:
  frequency_hz: 20.0
controllers:
  methane_crossover_mdot_p:
    type: proportional
    active_phases: [CLC, throttle, CLC_recover]
    inactive_phases: [prestart, startup, shutdown, rundown]
    reset_on_enter: [CLC]
    hold_when_inactive: false
    inputs:
      target: targets.mdot_total
      measurement: measurements.mdot_total
    output: methane_crossover_valve.command
    parameters:
      bias: 0.5
      gain: 0.08
      lower_limit: 0.05
      upper_limit: 1.00
  lox_crossover_of_p:
    type: proportional
    active_phases: [CLC, throttle, CLC_recover]
    inactive_phases: [prestart, startup, shutdown, rundown]
    reset_on_enter: [CLC]
    hold_when_inactive: false
    inputs:
      target: targets.OF
      measurement: measurements.OF
    output: lox_crossover_valve.command
    parameters:
      bias: 0.50
      gain: -5
      lower_limit: 0.05
      upper_limit: 1.00
