name: ffsc_dae_acceptance_operating_conditions
targets:
  mdot_total:
    schedule:
      type: table
      values:
        - [0.0, 40.0]
        - [9.999, 40.0]
        - [10.0, 30.0]
        - [19.999, 30.0]
        - [20.0, 40.0]
        - [25.0, 40.0]
  OF:
    schedule:
      type: table
      values:
        - [0.0, 3.0]
        - [5.0, 3.0]
        - [25.0, 3.4]
