name: gg_single_shaft_methalox_controller
evaluation:
  frequency_hz: 10.0
controllers:
  lox_generator_mdot_p:
    type: pid
    active_phases: [CLC]
    inputs:
      target: targets.mdot_total
      measurement: measurements.mdot_total
    output: lox_generator_valve.command
    parameters:
      bias: 0.5
      proportional_gain: 0.1
      integral_gain: 0.25
      derivative_gain: 0.
      lower_limit: 0.00
      upper_limit: 1.00
  methane_generator_of_p:
    type: pid
    active_phases: [CLC]
    inputs:
      target: targets.OF
      measurement: measurements.OF
    output: methane_generator_valve.command
    parameters:
      bias: 0
      proportional_gain: -5.5
      integral_gain: -4
      derivative_gain: 0.0001
      lower_limit: 0.00
      upper_limit: 1.00
