name: gg_single_shaft_methalox_timings
events:
  - target: main_lox_valve.command
    schedule:
      type: step
      time: 25.0
      initial: 1.0
      final: 0.0
  - target: main_methane_valve.command
    schedule:
      type: step
      time: 25.0
      initial: 1.0
      final: 0.0
  - target: lox_generator_valve.command
    schedule:
      type: step
      time: 25.0
      initial: 0.5
      final: 0.0
  - target: methane_generator_valve.command
    schedule:
      type: step
      time: 25.0
      initial: 0.4
      final: 0.0
