name: gg_single_shaft_methalox_transients
transients:
  methane_generator_valve:
    type: first_order
    input: methane_generator_valve.command
    output: methane_generator_valve.position
    initial: 0.5
    parameters:
      time_constant: 0.15
      lower_limit: 0.05
      upper_limit: 1.0
  lox_generator_valve:
    type: first_order
    input: lox_generator_valve.command
    output: lox_generator_valve.position
    initial: 0.5
    parameters:
      time_constant: 0.15
      lower_limit: 0.05
      upper_limit: 1.0
  main_lox_valve:
    type: first_order
    input: main_lox_valve.command
    output: main_lox_valve.position
    initial: 0.9
    parameters:
      time_constant: 0.25
      lower_limit: 0.0
      upper_limit: 1.0
  main_methane_valve:
    type: first_order
    input: main_methane_valve.command
    output: main_methane_valve.position
    initial: 0.9
    parameters:
      time_constant: 0.25
      lower_limit: 0.0
      upper_limit: 1.0
