name: chamber_startup_transient_timings
events:
  - target: ox_valve.command
    schedule:
      type: table
      values:
        - [0.0, 0.0]
        - [0.149, 0.0]
        - [0.15, 1.0]
        - [3.0, 1.0]
  - target: fuel_valve.command
    schedule:
      type: table
      values:
        - [0.0, 0.0]
        - [0.149, 0.0]
        - [0.15, 1.0]
        - [3.0, 1.0]
